In [1]:
import numpy as np

In [2]:
def sigmoid (x): return 1/(1 + np.exp(-x))

In [3]:
w_a = np.array([0.45,0.25])

In [4]:
w_i = np.array([0.95,0.8])

In [5]:
w_f = np.array([0.7,0.45])

In [6]:
w_o = np.array([0.6,0.4])

In [7]:
u_a = np.array([0.15])

In [8]:
u_i = np.array([0.8])

In [9]:
u_f = np.array([1.8])

In [10]:
u_o = np.array([0.25])

In [11]:
b_a = np.array([0.2])

In [12]:
b_i = np.array([0.65])

In [13]:
b_f = np.array([0.15])

In [14]:
b_o = np.array([0.1])

In [15]:
x_0 = np.array([1,2])

In [16]:
x_1 = np.array([0.5,3])

In [17]:
l0 = 0.5

In [18]:
l1 = 1.25

In [19]:
a_0 = np.tanh(np.dot(w_a,x_0) + np.dot(u_a,0) + b_a)

In [20]:
a_0

array([ 0.81775408])

In [21]:
i_0 = sigmoid(np.dot(w_i,x_0) + u_i*0 + b_i)

In [22]:
i_0

array([ 0.96083428])

In [23]:
f_0 = sigmoid(np.dot(w_f,x_0) + u_f*0 + b_f)

In [24]:
f_0

array([ 0.8519528])

In [25]:
o_0 = sigmoid(np.dot(w_o,x_0) + u_o*0 + b_o)

In [26]:
o_0

array([ 0.81757448])

In [27]:
state_0 = np.multiply(a_0,i_0) + np.multiply(f_0,0) 

In [28]:
state_0

array([ 0.78572615])

In [29]:
out_0 = np.multiply(np.tanh(state_0),o_0)

In [30]:
out_0

array([ 0.5363134])