In [1]:
x = 35
y = x + 5
print(y)

40


#### Equivalente em tensorflow

In [3]:
import tensorflow as tf

x = tf.constant(35, name='x')
y = tf.Variable(x + 5, name='y')

print(y)

Tensor("y/read:0", shape=(), dtype=int32)


#### ficou estranho... vamos dar uma corrigida

In [4]:
import tensorflow as tf

x = tf.constant(35, name='x')
y = tf.Variable(x + 5, name='y')

model = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(model)
    print(session.run(y))

40


#### constantes também podem ser matrizes

In [6]:
import tensorflow as tf


x = tf.constant([35, 40, 45], name='x')
y = tf.Variable(x + 5, name='y')


model = tf.global_variables_initializer()

with tf.Session() as session:
	session.run(model)
	print(session.run(y))

[40 45 50]


<h5>
Gerar uma matriz NumPy de 10.000 números aleatórios (chamados x) e criar uma variável armazenando a equação

$Y= 5x^2- 3 x + 15$

</h5>

In [30]:
import numpy as np
data = np.random.randint(1000, size=10000)
print(data[:10])

[241 215 268 136 523 208 733 566 527 118]


In [34]:
import tensorflow as tf


x = tf.constant(data, name='x')
y = tf.Variable(5*x ** 2 - 3 * x + 15, name='y')


model = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(model)
    data_calc = session.run(y)
    print(data_calc[:10])

[ 289697  230495  358331   92087 1366091  215711 2684261 1600097 1387079
   69281]


#### um contador

In [36]:
import tensorflow as tf


x = tf.Variable(0, name='x')

model = tf.global_variables_initializer()

with tf.Session() as session:
    for i in range(5):
        session.run(model)
        x = x + 1
        print(session.run(x))

1
2
3
4
5


### Placeholders

<p>
Até agora temos usado variáveis para gerenciar nossos dados, mas há uma estrutura mais básica, a placeholder. A placeholderé simplesmente uma variável à qual atribuiremos dados posteriormente. Ele nos permite criar nossas operações e construir nosso gráfico de computação, sem precisar dos dados. Em TensorFlow terminologia, então, alimentamos os dados para o gráfico através desses espaços reservados.
</p>

In [38]:
import tensorflow as tf

x = tf.placeholder("float", None)
y = x * 2

with tf.Session() as session:
    result = session.run(y, feed_dict={x: [1, 2, 3, 4]})
    print(result)

[ 2.  4.  6.  8.]


#### usando matriz

In [39]:
import tensorflow as tf

x = tf.placeholder("float", [None, 3])
y = x * 2

with tf.Session() as session:
    x_data = [[1, 2, 3],
              [4, 5, 6],]
    result = session.run(y, feed_dict={x: x_data})
    print(result)

[[  2.   4.   6.]
 [  8.  10.  12.]]


A primeira dimensão do espaço reservado é None, o que significa que podemos ter qualquer número de linhas. A segunda dimensão é fixada em 3, o que significa que cada linha precisa ter três colunas de dados.

### Referência: http://learningtensorflow.com/index.html